name: Destroy RDS Infra 

on:
  workflow_dispatch:

jobs:
  destroy-rds:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_vpc_soat: ${{ vars.VPC_ID }}
          TF_VAR_subnet_a_id: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b_id: ${{ vars.SUBNET_B }}
          TF_VAR_security_group_load_balancer: ${{ vars.SG_LOAD_BALANCER }}